var
a:integer;
begin
writeln('yek adad vared konid');
readln(a);
if a=1 then
writeln('farda movafaghiyate bozorgy kasb khahy kard');
if a=2 then
writeln('farda etefaghe bady barayat nyoftad');
if a=3 then
writeln('etefaghe khooby barayat myoftad');
if a=4 then
writeln('POOCH!!!');
if a=5 then
writeln('omydvar bash');
if a=6 then
writeln('ganje bad avarde be dast khahy avard');
if a=7 then
writeln('to farda mimiry!');
if a=8 then
writeln('be an chyzy ke mykhasty myresy');
if a=9 then
writeln('ganjy ra az dast khahy dad');
readln;
end.